version: '3.8'
services:
  core:
    container_name: fluxcred_core_api
    restart: unless-stopped
    image: srmasset/fluxcred-core-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fluxcred
      SPRING_DATASOURCE_USERNAME: srmasset
      SPRING_DATASOURCE_PASSWORD: Admin!
    depends_on:
      - db
    networks:
      - fluxcred_network
    labels:
      NAME: "fluxcred"

  db:
    container_name: fluxcred_db
    restart: unless-stopped
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fluxcred
      POSTGRES_USER: srmasset
      POSTGRES_PASSWORD: Admin!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql/:/var/lib/postgresql/data
    networks:
      - fluxcred_network
    labels:
      NAME: "fluxcred"

  rabbitmq:
    container_name: fluxcred_rabbit
    restart: unless-stopped
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "srmasset"
      RABBITMQ_DEFAULT_PASS: "Admin!"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    labels:
      NAME: "fluxcred"

networks:
  fluxcred_network:
    external: true